-- Create DB and tables for SQL Server
-- Run in SSMS
CREATE DATABASE AuthDB;
GO
USE AuthDB;
GO

IF OBJECT_ID('Users','U') IS NULL
BEGIN
CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(200) NOT NULL UNIQUE,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(500) NOT NULL,
  FailedAttempts INT DEFAULT 0,
  CreatedAt DATETIME DEFAULT GETDATE()
);
END

IF OBJECT_ID('RefreshTokens','U') IS NULL
BEGIN
CREATE TABLE RefreshTokens (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL,
  Token NVARCHAR(500) NOT NULL UNIQUE,
  ExpiresAt DATETIME NOT NULL,
  CreatedAt DATETIME DEFAULT GETDATE(),
  CONSTRAINT FK_RT_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
END

IF OBJECT_ID('OtpCodes','U') IS NULL
BEGIN
CREATE TABLE OtpCodes (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL,
  Code NVARCHAR(6) NOT NULL,
  ExpiresAt DATETIME NOT NULL,
  CreatedAt DATETIME DEFAULT GETDATE(),
  CONSTRAINT FK_Otp_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
END
